import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ gap: 20, display: 'flex', flexGrow: '1', flexBasis: 200, maxWidth: 1200, margin: '0 auto' }}>
          <Link href={'/'}>home</Link>
          <Link href={'/product'}>produk</Link>
          <Link href={'/post'}>post</Link>
        </header>
        <h2>{}</h2>
        
        {props.children}
      </body>
    </html>
  );
}
